-- Massive Data Seed for Nationwide Blood Banks
-- Run this in your Supabase SQL Editor

INSERT INTO public.blood_banks (name, address, city, state, verified) VALUES
  ('Red Cross Blood Bank', '1 Red Cross Road', 'Delhi', 'Delhi', true),
  ('AIIMS Blood Centre', 'Ansari Nagar East', 'Delhi', 'Delhi', true),
  ('Rotary Blood Bank', 'Tughlakabad Institutional Area', 'Delhi', 'Delhi', true),
  ('Tata Memorial Hospital Blood Bank', 'Dr. E Borges Road, Parel', 'Mumbai', 'Maharashtra', true),
  ('Sankalp Blood Bank', 'Andheri West', 'Mumbai', 'Maharashtra', true),
  ('KEM Hospital Blood Bank', 'Acharya Donde Marg, Parel', 'Mumbai', 'Maharashtra', true),
  ('Lions Blood Bank', 'MG Road, Camp', 'Pune', 'Maharashtra', true),
  ('NIMHANS Blood Bank', 'Hosur Road, Lakkasandra', 'Bangalore', 'Karnataka', true),
  ('Rotary TTK Blood Bank', 'New Thippasandra', 'Bangalore', 'Karnataka', true),
  ('Lions Blood Bank', 'Egmore', 'Chennai', 'Tamil Nadu', true),
  ('Rajiv Gandhi Government General Hospital Blood Bank', 'Park Town', 'Chennai', 'Tamil Nadu', true),
  ('CMC Vellore Blood Bank', 'Ida Scudder Road', 'Vellore', 'Tamil Nadu', true),
  ('Chiranjeevi Blood Bank', 'Jubilee Hills', 'Hyderabad', 'Telangana', true),
  ('NTR Trust Blood Bank', 'Banjara Hills', 'Hyderabad', 'Telangana', true),
  ('Indian Red Cross Society', 'Vidhana Soudha', 'Hyderabad', 'Telangana', true),
  ('Gujarat Research & Medical Institute Blood Bank', 'Shahibag', 'Ahmedabad', 'Gujarat', true),
  ('Prathama Blood Centre', 'Vasna', 'Ahmedabad', 'Gujarat', true),
  ('Surat Raktadan Kendra', 'Udhna Magdalla Road', 'Surat', 'Gujarat', true),
  ('Kolkata Medical College Blood Bank', 'College Square', 'Kolkata', 'West Bengal', true),
  ('Lions Blood Bank', 'Deshapriya Park', 'Kolkata', 'West Bengal', true),
  ('SMS Hospital Blood Bank', 'JLN Marg', 'Jaipur', 'Rajasthan', true),
  ('Mahatma Gandhi Hospital Blood Bank', 'Sitapura', 'Jaipur', 'Rajasthan', true),
  ('PGI Blood Bank', 'Sector 12', 'Chandigarh', 'Chandigarh', true),
  ('IGMC Blood Bank', 'Lakkar Bazaar', 'Shimla', 'Himachal Pradesh', true),
  ('Doon Hospital Blood Bank', 'Dehradun City', 'Dehradun', 'Uttarakhand', true),
  ('SGPGIMS Blood Bank', 'Raebareli Road', 'Lucknow', 'Uttar Pradesh', true),
  ('KGMU Blood Bank', 'Chowk', 'Lucknow', 'Uttar Pradesh', true),
  ('PMCH Blood Bank', 'Ashok Rajpath', 'Patna', 'Bihar', true),
  ('RIMS Blood Bank', 'Bariatu', 'Ranchi', 'Jharkhand', true),
  ('SCB Medical College Blood Bank', 'Manglabag', 'Cuttack', 'Odisha', true),
  ('Capital Hospital Blood Bank', 'Unit-6', 'Bhubaneswar', 'Odisha', true),
  ('GMC Blood Bank', 'Bhangagarh', 'Guwahati', 'Assam', true),
  ('Civil Hospital Blood Bank', 'Police Bazar', 'Shillong', 'Meghalaya', true),
  ('RIMS Blood Bank', 'Lamphelpat', 'Imphal', 'Manipur', true),
  ('GMC Blood Bank', 'Bambolim', 'Goa', 'Goa', true),
  ('Medical College Blood Bank', 'Kumarapuram', 'Thiruvananthapuram', 'Kerala', true),
  ('Amrita Hospital Blood Bank', 'Edappally', 'Kochi', 'Kerala', true),
  ('JIPMER Blood Bank', 'Dhanvantri Nagar', 'Puducherry', 'Puducherry', true),
  ('MY Hospital Blood Bank', 'Residency Area', 'Indore', 'Madhya Pradesh', true),
  ('AIIMS Bhopal Blood Bank', 'Saket Nagar', 'Bhopal', 'Madhya Pradesh', true)
ON CONFLICT DO NOTHING;
